# Generated by Django 4.1.7 on 2023-04-26 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted')),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 26, 22, 26, 55, 870025))),
            ],
            options={
                'db_table': 'Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
