# Generated by Django 4.1.7 on 2023-04-27 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_blog_posted_alter_coment_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='coments',
            field=models.ManyToManyField(null=True, to='main.coment'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 3, 6, 23, 860790)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 3, 6, 23, 859790)),
        ),
    ]
