# Generated by Django 4.2 on 2023-04-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_coment_blog_blog_coments_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 17, 15, 38, 507677)),
        ),
        migrations.AlterField(
            model_name='coment',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 17, 15, 38, 507677)),
        ),
    ]
